import React from 'react';
import { GeneratedPlan, Repo } from '../types';
import StepCard from './StepCard';
import { Download, CheckCircle, RotateCcw } from 'lucide-react';

interface PlanDisplayProps {
  plan: GeneratedPlan;
  repo: Repo;
  onReset: () => void;
}

const PlanDisplay: React.FC<PlanDisplayProps> = ({ plan, repo, onReset }) => {
  
  const handleDownload = () => {
    const mdContent = `# ${plan.title}
    
## Executive Summary
${plan.summary}

## Implementation Steps

${plan.steps.map(step => `
### Step ${step.id}: ${step.title}
**Complexity:** ${step.complexity}
**Files:** ${step.affectedFiles.join(', ') || 'N/A'}

${step.description}

**Rationale:**
${step.rationale}

**Technical Details:**
${step.technicalDetails}

---
`).join('\n')}

Generated by GitArchitect
`;

    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TODO-${repo.name}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-4xl mx-auto space-y-6 pb-20">
      {/* Header Card */}
      <div className="bg-gradient-to-br from-gray-900 to-gray-800 border border-gray-700 rounded-2xl p-8 shadow-2xl relative overflow-hidden">
        <div className="absolute top-0 right-0 p-4 opacity-10">
          <Download className="w-64 h-64" />
        </div>
        
        <div className="relative z-10">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
                <div>
                    <h2 className="text-3xl font-bold text-white tracking-tight">{plan.title}</h2>
                    <p className="text-emerald-400 font-medium mt-1">Targeting: {repo.full_name}</p>
                </div>
                <div className="flex items-center gap-3">
                    <button 
                        onClick={onReset}
                        className="flex items-center gap-2 px-4 py-2 rounded-lg bg-gray-800 text-gray-300 hover:bg-gray-700 hover:text-white transition-all border border-gray-700 text-sm"
                    >
                        <RotateCcw className="w-4 h-4" /> New Plan
                    </button>
                    <button 
                        onClick={handleDownload}
                        className="flex items-center gap-2 px-4 py-2 rounded-lg bg-emerald-600 text-white hover:bg-emerald-500 transition-all shadow-lg shadow-emerald-900/40 text-sm font-semibold"
                    >
                        <Download className="w-4 h-4" /> Download .md
                    </button>
                </div>
            </div>
            
            <div className="bg-gray-950/50 rounded-xl p-6 border border-gray-700/50 backdrop-blur-sm">
                <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-2">Executive Summary</h3>
                <p className="text-gray-200 leading-relaxed">{plan.summary}</p>
            </div>
        </div>
      </div>

      <div className="flex items-center gap-4 py-2">
          <div className="h-px flex-1 bg-gray-800"></div>
          <span className="text-gray-500 text-sm font-mono uppercase tracking-widest">Action Plan</span>
          <div className="h-px flex-1 bg-gray-800"></div>
      </div>

      {/* Steps List */}
      <div className="space-y-4">
        {plan.steps.map((step) => (
          <StepCard key={step.id} step={step} repoName={repo.full_name} />
        ))}
      </div>
      
      <div className="flex justify-center pt-8 text-gray-600 text-sm">
        <p className="flex items-center gap-2">
            <CheckCircle className="w-4 h-4" /> End of Plan
        </p>
      </div>
    </div>
  );
};

export default PlanDisplay;
