import React, { useState } from 'react';
import { GeneratedPlan, Repo } from '../types';
import StepCard from './StepCard';
import { Download, CheckCircle, RotateCcw, MessageSquareCode, Sparkles, ShieldAlert, Globe } from 'lucide-react';
import { refactorPlan } from '../services/gemini';
import { getRepoStructure } from '../services/github';

interface PlanDisplayProps {
  plan: GeneratedPlan;
  repo: Repo;
  onReset: () => void;
  onUpdatePlan: (newPlan: GeneratedPlan) => void;
}

const PlanDisplay: React.FC<PlanDisplayProps> = ({ plan, repo, onReset, onUpdatePlan }) => {
  const [refactorPrompt, setRefactorPrompt] = useState('');
  const [isRefactoring, setIsRefactoring] = useState(false);
  const [showResearch, setShowResearch] = useState(false);

  const handleDownload = () => {
    const mdContent = `# ${plan.title}
    
## Executive Summary
${plan.summary}

## Safety & Research Context
${plan.researchNotes || "No specific external research notes."}

## Implementation Steps

${plan.steps.map(step => `
### Step ${step.id}: ${step.title}
**Complexity:** ${step.complexity}
**Files:** ${step.affectedFiles.join(', ') || 'N/A'}

${step.description}

**Rationale:**
${step.rationale}

**Safety Checks:**
${step.safetyChecks.map(s => `- [ ] ${s}`).join('\n')}

**Technical Details:**
${step.technicalDetails}

---
`).join('\n')}

Generated by GitArchitect
`;

    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TODO-${repo.name}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleRefactor = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!refactorPrompt.trim()) return;

    setIsRefactoring(true);
    try {
        const structure = await getRepoStructure(repo.full_name);
        const newPlan = await refactorPlan(plan, refactorPrompt, { 
            name: repo.full_name, 
            structure 
        });
        onUpdatePlan(newPlan);
        setRefactorPrompt('');
    } catch (error) {
        alert("Failed to update plan. Please try again.");
    } finally {
        setIsRefactoring(false);
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto space-y-6 pb-20">
      
      {/* Architect Interface (Refactor Chat) */}
      <div className="bg-indigo-900/20 border border-indigo-500/30 rounded-2xl p-6 shadow-xl backdrop-blur-sm animate-fade-in">
        <div className="flex items-start gap-4">
             <div className="p-3 bg-indigo-500/20 rounded-xl border border-indigo-500/30 hidden sm:block">
                 <Sparkles className="w-6 h-6 text-indigo-400" />
             </div>
             <div className="flex-1">
                 <h3 className="text-lg font-bold text-white mb-1 flex items-center gap-2">
                    <span className="sm:hidden"><Sparkles className="w-4 h-4 text-indigo-400" /></span>
                    Plan Architect
                 </h3>
                 <p className="text-sm text-indigo-300 mb-4">
                     Reviewing the plan? Tell me if you need more safety checks, if a step is too complex, or if I missed a requirement. I will restructure the entire plan for you.
                 </p>
                 
                 <form onSubmit={handleRefactor} className="relative">
                     <input 
                        type="text"
                        value={refactorPrompt}
                        onChange={(e) => setRefactorPrompt(e.target.value)}
                        placeholder="e.g., 'Make step 2 safer with a database backup' or 'Split step 4 into two parts'..."
                        className="w-full bg-gray-950/80 border border-indigo-500/30 rounded-xl pl-4 pr-14 py-3 text-white placeholder-indigo-400/50 focus:outline-none focus:border-indigo-400 focus:ring-1 focus:ring-indigo-400 transition-all"
                        disabled={isRefactoring}
                     />
                     <button 
                        type="submit"
                        disabled={!refactorPrompt.trim() || isRefactoring}
                        className="absolute right-2 top-2 bottom-2 bg-indigo-600 hover:bg-indigo-500 text-white px-3 rounded-lg flex items-center justify-center transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                     >
                        {isRefactoring ? <div className="animate-spin w-4 h-4 border-2 border-white/30 border-t-white rounded-full"></div> : <MessageSquareCode className="w-5 h-5" />}
                     </button>
                 </form>
             </div>
        </div>
      </div>

      {/* Main Plan Card */}
      <div className="bg-gradient-to-br from-gray-900 to-gray-800 border border-gray-700 rounded-2xl p-8 shadow-2xl relative overflow-hidden">
        <div className="absolute top-0 right-0 p-4 opacity-10">
          <Download className="w-64 h-64" />
        </div>
        
        <div className="relative z-10">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
                <div>
                    <h2 className="text-3xl font-bold text-white tracking-tight">{plan.title}</h2>
                    <p className="text-emerald-400 font-medium mt-1">Targeting: {repo.full_name}</p>
                </div>
                <div className="flex items-center gap-3">
                    <button 
                        onClick={onReset}
                        className="flex items-center gap-2 px-4 py-2 rounded-lg bg-gray-800 text-gray-300 hover:bg-gray-700 hover:text-white transition-all border border-gray-700 text-sm"
                    >
                        <RotateCcw className="w-4 h-4" /> New Plan
                    </button>
                    <button 
                        onClick={handleDownload}
                        className="flex items-center gap-2 px-4 py-2 rounded-lg bg-emerald-600 text-white hover:bg-emerald-500 transition-all shadow-lg shadow-emerald-900/40 text-sm font-semibold"
                    >
                        <Download className="w-4 h-4" /> Download .md
                    </button>
                </div>
            </div>
            
            <div className="bg-gray-950/50 rounded-xl p-6 border border-gray-700/50 backdrop-blur-sm space-y-4">
                <div>
                    <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-2">Executive Summary</h3>
                    <p className="text-gray-200 leading-relaxed">{plan.summary}</p>
                </div>
                
                {plan.researchNotes && (
                    <div className="pt-2 border-t border-gray-800/50">
                        <button 
                            onClick={() => setShowResearch(!showResearch)}
                            className="flex items-center gap-2 text-xs font-semibold text-blue-400 uppercase tracking-wider hover:text-blue-300 transition-colors"
                        >
                            <Globe className="w-3 h-3" />
                            {showResearch ? "Hide Research Context" : "Show Deep Research Notes"}
                        </button>
                        {showResearch && (
                            <div className="mt-3 text-sm text-gray-400 leading-relaxed bg-blue-900/10 p-4 rounded-lg border border-blue-900/20 animate-fade-in">
                                {plan.researchNotes}
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
      </div>

      <div className="flex items-center gap-4 py-2">
          <div className="h-px flex-1 bg-gray-800"></div>
          <span className="text-gray-500 text-sm font-mono uppercase tracking-widest">Action Plan</span>
          <div className="h-px flex-1 bg-gray-800"></div>
      </div>

      {/* Steps List */}
      <div className="space-y-4">
        {plan.steps.map((step) => (
          <StepCard key={step.id} step={step} repoName={repo.full_name} />
        ))}
      </div>
      
      <div className="flex justify-center pt-8 text-gray-600 text-sm">
        <p className="flex items-center gap-2">
            <CheckCircle className="w-4 h-4" /> End of Plan
        </p>
      </div>
    </div>
  );
};

export default PlanDisplay;